spring.application.name=pjwt
logging.level.org.springframework.security.*=debug
logging.level.ru.ls.pjwt.*=debug

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.url=jdbc:postgresql://localhost:5433/jwt_pg_test
