spring:
  config:
    import: file:.env[.properties]
  application:
    name: pjwt
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: ${DOCKER_DB_USERNAME:postgres}
    password: ${DOCKER_BD_PASSWORD:12345}
    url: jdbc:postgresql://${DOCKER_DB_URL:localhost:5433}/${DOCKER_DB_NAME:jwt_pg_test}

logging:
  level:
    org.springframework.security.*: debug
    ru.ls.pjwt.*: debug

pjwt:
  application:
    name: jwt-authorization-api-1445
  format:
    date-format: yyyy-MM-dd__HH:mm:ss
  authorities:
    user: USER
    mod: MODERATOR
    admin: ADMIN
  jwt:
    secret-key-string: ${JWT_SECRET_KEY}
    access-token: access
    refresh-token: refresh
    access-token-expiration-minutes: 10
    refresh-token-expiration-days: 14
  exceptions:
    bad-credentials: BAD_CREDENTIALS
    account-expired: ACCOUNT_EXPIRED
    account-locked: ACCOUNT_LOCKED
    credentials-expired: CREDENTIALS_EXPIRED
    account-disabled: ACCOUNT_DISABLED
    user-exists: USER_ALREADY_EXISTS
    email-exists: EMAIL_ALREADY_EXISTS
    validation-failed: VALIDATION_FAILED
    refresh-token-compromised: "refresh token was compromised. you may be get hacked. please re-login"