logging:
  level:
    org.springframework.security.*: debug
    ru.ls.pjwt.*: debug

spring:
  config:
    import:
      - "optional:file:.env/local/dev-migration.properties"
  jpa:
    show-sql: true
  flyway:
    placeholders:
      admin.name: ${DB_ADMIN_NAME}
      admin.email: ${DB_ADMIN_EMAIL}
      admin.password: ${DB_ADMIN_PASSWORD}
      authorities.user: ${DB_AUTHORITY_USER}
      authorities.moderator: ${DB_AUTHORITY_MODERATOR}
      authorities.admin: ${DB_AUTHORITY_ADMIN}
      usernames.user: ${DB_USERNAMES_USER}
      usernames.moderator: ${DB_USERNAMES_MODERATOR}
      usernames.admin: ${DB_USERNAMES_ADMIN}
      passwords.standard: ${DB_DEFAULT_TEST_PASSWORD}
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/dev
dev:
  test-controller:
    public-response: public data
    protected-response: your details
    user-only-response: userOnly data
    admin-only-response: adminOnly data
    moder-only-response: moderOnly data
  test-users-passwords:
    standard: test
  test-users-names:
    user: ${DB_USERNAMES_USER}
    moderator: ${DB_USERNAMES_MODERATOR}
    admin: ${DB_USERNAMES_ADMIN}